CREATE TABLE IF NOT EXISTS user
(
    id BIGINT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    username VARCHAR(128) UNIQUE NOT NULL ,
    password VARCHAR(2048) NOT NULL,
    role INT NOT NULL DEFAULT 0,
    status INT NOT NULL DEFAULT 0,
    create_time BIGINT NOT NULL,
    token VARCHAR(2048),
    token_expired BIGINT NOT NULL DEFAULT 0
);